# Generated by Django 4.0.3 on 2022-12-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collectfavorites',
            fields=[
                ('field_id', models.AutoField(db_column='_id', primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('favorites_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CollectFavorites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('field_id', models.IntegerField(db_column='_id', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Favorites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('field_id', models.AutoField(db_column='_id', primary_key=True, serialize=False)),
                ('paper_id', models.TextField(blank=True, null=True)),
                ('like_count', models.IntegerField(blank=True, null=True)),
                ('collect_count', models.IntegerField(blank=True, null=True)),
                ('paper_name', models.CharField(blank=True, max_length=255, null=True)),
                ('read_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Paper',
                'managed': False,
            },
        ),
    ]
