# Generated by Django 4.0.3 on 2022-12-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_favorites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('field_id', models.AutoField(db_column='_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Like',
                'managed': False,
            },
        ),
    ]
