# Generated by Django 4.0.3 on 2022-12-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCode',
            fields=[
                ('field_id', models.AutoField(db_column='_id', primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'EmailCode',
                'managed': False,
            },
        ),
    ]
